// Generated by CoffeeScript 1.9.3
document.getElementById('blacklist').addEventListener('click', function() {
  return chrome.runtime.sendMessage({
    type: 'blacklist',
    name: 'bl'
  }, null);
});

document.getElementById('unblacklist').addEventListener('click', function() {
  return chrome.runtime.sendMessage({
    type: 'unblacklist',
    name: 'ubl'
  }, null);
});

//# sourceMappingURL=popup.js.map
